import esprima from "esprima-next";

export const DEFAULT_WIDTH = 3840;
export const DEFAULT_HEIGHT = 2160;

export const sampleCode = `var Gde;_.Ede=function(a){return((a.getDay()+6)%7-a.QAa+7)%7};_.Fde=function(a){return _.o6d(a.getFullYear(),a.getMonth())};Gde=function(a,b,c,d,e){a=new Date(a,b,c);d=d!==void 0?d:3;e=e||0;b=((a.getDay()+6)%7-e+7)%7;return a.valueOf()+((d-e+7)%7-b)*864E5};_.Hde=function(a,b){return a<b?a:b};var Ide,Jde,Lde;Ide=function(){};
_.Kde=function(a){if(typeof a=="number"){var b=new Ide;b.Ba=a;var c=a;if(c==0)c="Etc/GMT";else{var d=["Etc/GMT",c<0?"-":"+"];c=Math.abs(c);d.push(Math.floor(c/60)%100);c%=60;c!=0&&d.push(":",_.gl(c,2));c=d.join("")}b.wa=c;c=a;c==0?c="UTC":(d=["UTC",c<0?"+":"-"],c=Math.abs(c),d.push(Math.floor(c/60)%100),c%=60,c!=0&&d.push(":",c),c=d.join(""));a=Jde(a);b.Aa=[c,c];b.ka={Fjh:a,Akd:a};b.oa=[];return b}b=new Ide;b.wa=a.id;b.Ba=-a.std_offset;b.Aa=a.names;b.ka=a.names_ext;b.oa=a.transitions;return b};
Jde=function(a){var b=["GMT"];b.push(a<=0?"+":"-");a=Math.abs(a);b.push(_.gl(Math.floor(a/60)%100,2),":",_.gl(a%60,2));return b.join("")};Lde=function(a,b){b=Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes())/36E5;for(var c=0;c<a.oa.length&&b>=a.oa[c];)c+=2;return c==0?0:a.oa[c-1]};_.Mde=function(a,b){a=a.Ba-Lde(a,b);return a===-1440?0:a};Ide.prototype.dO=function(a){return this.Aa[Lde(this,a)>0?2:0]};var Pde,Qde,Ode;_.kF=function(a,b){this.oa=[];this.ka=b||_.RE;typeof a=="number"?Nde(this,a):Ode(this,a)};Pde=[/^'(?:[^']|'')*('|$)/,/^(?:G+|y+|Y+|M+|k+|S+|E+|a+|b+|B+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|V+|w+|z+|Z+)/,/^[^'GyYMkSEabBhKHcLQdmsvVwzZ]+/];Qde=function(a){return a.getHours?a.getHours():0};
Ode=function(a,b){for(Rde&&(b=b.replace(//g,""));b;){for(var c=b,d=0;d<Pde.length;++d){var e=b.match(Pde[d]);if(e){var f=e[0];b=b.substring(f.length);d==0&&(f=="''"?f="'":(f=f.substring(1,e[1]=="'"?f.length-1:f.length),f=f.replace(/''/g,"'")));a.oa.push({text:f,type:d});break}}if(c===b)throw Error("ji"+b);}};
_.kF.prototype.format=function(a,b){if(!a)throw Error("ki");var c=b?(a.getTimezoneOffset()-_.Mde(b,a))*6E4:0,d=c?new Date(a.getTime()+c):a,e=d;b&&d.getTimezoneOffset()!=a.getTimezoneOffset()&&(e=(d.getTimezoneOffset()-a.getTimezoneOffset())*6E4,d=new Date(d.getTime()+e),c+=c>0?-864E5:864E5,e=new Date(a.getTime()+c));c=[];for(var f=0;f<this.oa.length;++f){var g=this.oa[f].text;1==this.oa[f].type?c.push(Sde(this,g,a,d,e,b)):c.push(g)}return c.join("")};
var Nde=function(a,b){if(b<4)var c=a.ka.Ci[b];else if(b<8)c=a.ka.Ji[b-4];else if(b<12)c=a.ka.jj[b-8],c=c.replace("{1}",a.ka.Ci[b-8]),c=c.replace("{0}",a.ka.Ji[b-8]);else if(b===12)c=a.ka.Ci[0].replace(/[^EMd]*yy*[^EMd]*/,"");else if(b===13)c=a.ka.Ci[2].replace(/[^EMd]*yy*[^EMd]*/,"");else{Nde(a,10);return}Ode(a,c)},lF=function(a,b){b=String(b);a=a.ka||_.RE;if(a.gHa!==void 0&&!Tde){for(var c=[],d=0;d<b.length;d++){var e=b.charCodeAt(d);c.push(48<=e&&e<=57?String.fromCharCode(a.gHa+e-48):b.charAt(d))}b=
c.join("")}return b},Tde=!1,Rde=!1,Ude=function(a){if(!(a.getHours&&a.getSeconds&&a.getMinutes))throw Error("li");},Vde=function(a,b){Ude(b);b=Qde(b);return a.ka.hj[b>=12&&b<24?1:0]},Sde=function(a,b,c,d,e,f){var g=b.length;switch(b.charAt(0)){case "G":return c=d.getFullYear()>0?1:0,g>=4?a.ka.yj[c]:a.ka.kj[c];case "y":return c=d.getFullYear(),c<0&&(c=-c),g==2&&(c%=100),lF(a,_.gl(c,g));case "Y":return c=d.getFullYear(),e=d.getMonth(),d=d.getDate(),c=Gde(c,e,d,a.ka.Vi,a.ka.Li),c=(new Date(c)).getFullYear(),
c<0&&(c=-c),g==2&&(c%=100),lF(a,_.gl(c,g));case "M":a:switch(c=d.getMonth(),g){case 5:g=a.ka.zj[c];break a;case 4:g=a.ka.Wi[c];break a;case 3:g=a.ka.Xi[c];break a;default:g=lF(a,_.gl(c+1,g))}return g;case "k":return Ude(e),c=Qde(e)||24,lF(a,_.gl(c,g));case "S":return lF(a,(e.getMilliseconds()/1E3).toFixed(Math.min(3,g)).slice(2)+(g>3?_.gl(0,g-3):""));case "E":return c=d.getDay(),g>=4?a.ka.aj[c]:a.ka.Yi[c];case "a":return Vde(a,e);case "b":return Vde(a,e);case "B":return Vde(a,e);case "h":return Ude(e),
c=Qde(e)%12||12,lF(a,_.gl(c,g));case "K":return Ude(e),c=Qde(e)%12,lF(a,_.gl(c,g));case "H":return Ude(e),c=Qde(e),lF(a,_.gl(c,g));case "c":a:switch(c=d.getDay(),g){case 5:g=a.ka.Zi[c];break a;case 4:g=a.ka.Cj[c];break a;case 3:g=a.ka.ij[c];break a;default:g=lF(a,_.gl(c,1))}return g;case "L":a:switch(c=d.getMonth(),g){case 5:g=a.ka.Bj[c];break a;case 4:g=a.ka.Mi[c];break a;case 3:g=a.ka.nj[c];break a;default:g=lF(a,_.gl(c+1,g))}return g;case "Q":return c=Math.floor(d.getMonth()/3),g<4?a.ka.mj[c]:
a.ka.lj[c];case "d":return lF(a,_.gl(d.getDate(),g));case "m":return Ude(e),lF(a,_.gl(e.getMinutes?e.getMinutes():0,g));case "s":return Ude(e),lF(a,_.gl(e.getSeconds(),g));case "v":return(f||_.Kde(c.getTimezoneOffset())).wa;case "V":return a=f||_.Kde(c.getTimezoneOffset()),g<=2?a.wa:Lde(a,c)>0?a.ka.Lfe!==void 0?a.ka.Lfe:a.ka.DST_GENERIC_LOCATION:a.ka.Akd!==void 0?a.ka.Akd:a.ka.STD_GENERIC_LOCATION;case "w":return c=e.getFullYear(),d=e.getMonth(),e=e.getDate(),c=Gde(c,d,e,a.ka.Vi,a.ka.Li),lF(a,_.gl(Math.floor(Math.round((c-
(new Date((new Date(c)).getFullYear(),0,1)).valueOf())/864E5)/7)+1,g));case "z":return a=f||_.Kde(c.getTimezoneOffset()),g<4?a.dO(c):a.Aa[Lde(a,c)>0?3:1];case "Z":return d=f||_.Kde(c.getTimezoneOffset()),g<4?(g=-_.Mde(d,c),a=[g<0?"-":"+"],g=Math.abs(g),a.push(_.gl(Math.floor(g/60)%100,2),_.gl(g%60,2)),g=a.join("")):g=lF(a,Jde(_.Mde(d,c))),g;default:return""}};
}catch(e){_._DumpException(e)}
try{
var Wde,Xde,Yde;Wde=/^[]/;Xde=/^[]+/;_.Zde=function(a){this.ka=[];this.oa=_.RE;if(typeof a=="number"){a>11&&(a=10);if(a<4)var b=this.oa.Ci[a];else a<8?b=this.oa.Ji[a-4]:(b=this.oa.jj[a-8],b=b.replace("{1}",this.oa.Ci[a-8]),b=b.replace("{0}",this.oa.Ji[a-8]));Yde(this,b)}else Yde(this,a)};
Yde=function(a,b){for(var c=!1,d="",e=0;e<b.length;e++){var f=b.charAt(e);if(Wde.test(f))for(d.length>0&&(a.ka.push({text:d,count:0,d1a:!1,numeric:!1}),d=""),a.ka.push({text:" ",count:0,d1a:!1,numeric:!1});e<b.length-1&&b.charAt(e+1)==" ";)e++;else if(c)f=="'"?e+1<b.length&&b.charAt(e+1)=="'"?(d+="'",e++):c=!1:d+=f;else if("GyMdkHmsSEDabBhKzZvQL".indexOf(f)>=0){d.length>0&&(a.ka.push({text:d,count:0,d1a:!1,numeric:!1}),d="");for(var g=b.charAt(e),h=e+1;h<b.length&&b.charAt(h)==g;)h++;g=h-e;g<=0?h=
!1:(h="MydhHmsSDkK".indexOf(f),h=h>0||h==0&&g<3);a.ka.push({text:f,count:g,d1a:!1,numeric:h});e+=g-1}else f=="'"?e+1<b.length&&b.charAt(e+1)=="'"?(d+="'",e++):c=!0:d+=f}d.length>0&&a.ka.push({text:d,count:0,d1a:!1,numeric:!1});b=!1;for(c=0;c<a.ka.length;c++)a.ka[c].numeric?!b&&c+1<a.ka.length&&a.ka[c+1].numeric&&(b=!0,a.ka[c].d1a=!0):b=!1};
_.Zde.prototype.parse=function(a,b,c){var d=!1,e=!1;c&&(d=c.kBh||!1,e=c.validate||!1);if(d)for(c=0;c<this.ka.length;c++){var f=this.ka[c];if(f.count>0&&("abBhHkKm".indexOf(f.text.charAt(0))<0||f.count>2||f.d1a))throw Error("mi"+f.text.charAt(0));}f=new $de;c=[0];f.Ka=-1;for(var g=0;g<this.ka.length&&!(d&&c[0]>=a.length);g++){if(this.ka[g].count==0){a:{var h=a;var l=c,m=this.ka[g],q=d;if(m.text.match(Wde)!=null){if(m=l[0],aee(h,l),l[0]>m){h=!0;break a}}else{if(h.indexOf(m.text,l[0])==l[0]){l[0]+=
m.text.length;h=!0;break a}if(q&&m.text.indexOf(h.substring(l[0]))==0){l[0]+=h.length-l[0];h=!0;break a}}h=!1}if(h)continue;return 0}if(this.ka[g].d1a){a:{l=a;m=c;q=g;var r=m[0],w=0;for(h=q;h<this.ka.length;h++){var x=this.ka[h],B=x.count;if(B===0)break;if(h==q&&(B-=w,w++,B==0)){h=0;break a}var C=h>q&&x.numeric,N=m[0];if(!bee(this,l,m,x,B,f,!1)||C&&m[0]-N<B)h=q-1,m[0]=r}h-=q}if(h<=0)return 0;g+=h-1}else if(!bee(this,a,c,this.ka[g],0,f,d))return 0}a:{a=e;if(b==null)throw Error("ni");f.era!=void 0&&
f.year!=void 0&&f.era==0&&f.year>0&&(f.year=-(f.year-1));f.year!=void 0&&b.setFullYear(f.year);d=b.getDate();b.setDate(1);f.month!=void 0&&b.setMonth(f.month);f.day!=void 0?b.setDate(f.day):(e=_.o6d(b.getFullYear(),b.getMonth()),b.setDate(d>e?e:d));typeof b.setHours==="function"&&(f.hours==void 0&&(f.hours=b.getHours()),f.hours<12&&(f.Ga!=void 0&&f.Ga>0?f.hours+=12:f.wa!==void 0&&("isPm noon afternoon1 afternoon2 evening1 evening2".split(" ").includes(f.wa)||["night1","night2"].includes(f.wa)&&f.hours>=
6)&&(f.hours+=12)),b.setHours(f.hours));typeof b.setMinutes==="function"&&f.minutes!=void 0&&b.setMinutes(f.minutes);typeof b.setSeconds==="function"&&f.VO!=void 0&&b.setSeconds(f.VO);typeof b.setMilliseconds==="function"&&f.ka!=void 0&&b.setMilliseconds(f.ka);if(a&&(f.year&&f.year!=b.getFullYear()||f.month&&f.month!=b.getMonth()||f.day&&f.day!=b.getDate()||f.hours&&f.hours>=24||f.minutes&&f.minutes>=60||f.VO&&f.VO>=60||f.ka&&f.ka>=1E3))b=!1;else{f.Aa!=void 0&&(a=b.getTimezoneOffset(),b.setTime(b.getTime()+
(f.Aa-a)*6E4));f.Ba&&(a=new Date,a.setFullYear(a.getFullYear()-80),b.getTime()<a.getTime()&&b.setFullYear(a.getFullYear()+100));if(f.oa!=void 0)if(f.day==void 0)f=(7+f.oa-b.getDay())%7,f>3&&(f-=7),a=b.getMonth(),b.setDate(b.getDate()+f),b.getMonth()!=a&&b.setDate(b.getDate()+(f>0?-7:7));else if(f.oa!=b.getDay()){b=!1;break a}b=!0}}return b?c[0]:0};
var bee=function(a,b,c,d,e,f,g){aee(b,c);if(d.numeric&&e>0&&c[0]+e>b.length)return!1;switch(d.text.charAt(0)){case "G":return cee(b,c,[a.oa.kj],function(h){return f.era=h}),!0;case "M":case "L":return dee(a,b,c,e,d,f);case "E":return cee(b,c,[a.oa.aj,a.oa.Yi],function(h){return f.oa=h});case "B":case "b":return e=[],a=[[].concat(a.oa.hj)],e.push("isAm"),e.push("isPm"),b=cee(b,c,a,function(h){return f.Ka=h},g),f.wa=e[f.Ka],g?b:!0;case "a":return b=cee(b,c,[a.oa.hj],function(h){return f.Ga=h},g),g?
b:!0;case "y":return eee(a,b,c,d,e,f);case "Q":return cee(b,c,[a.oa.lj,a.oa.mj],function(h){f.month=h*3;f.day=1});case "d":return fee(a,b,c,d,e,function(h){f.day=h}),!0;case "S":return gee(a,b,c,e,f);case "h":case "K":case "H":case "k":return b=fee(a,b,c,d,e,function(h){f.hours=d.text.charAt(0)==="h"&&h===12?0:h},g),g?b:!0;case "m":return b=fee(a,b,c,d,e,function(h){f.minutes=h},g),g?b:!0;case "s":return fee(a,b,c,d,e,function(h){f.VO=h}),!0;case "z":case "Z":case "v":return hee(a,b,c,f);default:return!1}},
eee=function(a,b,c,d,e,f){var g=c[0];e=iee(a,b,c,e);e===null&&(e=iee(a,b,c,0,!0));if(e===null)return!1;e>=0&&c[0]-g==2&&d.count==2?(a=e,b=(new Date).getFullYear()-80,c=b%100,f.Ba=a==c,a+=Math.floor(b/100)*100+(a<c?100:0),f.year=a):f.year=e;return!0},dee=function(a,b,c,d,e,f){return e.numeric&&fee(a,b,c,e,d,function(g){f.month=g-1})?!0:cee(b,c,[a.oa.Wi,a.oa.Mi,a.oa.Xi,a.oa.nj],function(g){f.month=g})},gee=function(a,b,c,d,e){var f=c[0];a=iee(a,b,c,d);if(a===null)return!1;c=c[0]-f;e.ka=c<3?a*Math.pow(10,
3-c):Math.round(a/Math.pow(10,c-3));return!0},hee=function(a,b,c,d){b.indexOf("GMT",c[0])==c[0]&&(c[0]+=3);if(c[0]>=b.length)return d.Aa=0,!0;var e=c[0],f=iee(a,b,c,0,!0);if(f===null)return!1;if(c[0]<b.length&&b.charAt(c[0])==":"){var g=f*60;c[0]++;f=iee(a,b,c,0);if(f===null)return!1;g+=f}else g=f,g=g<24&&c[0]-e<=3?g*60:g%100+g/100*60;d.Aa=-g;return!0},fee=function(a,b,c,d,e,f,g){g=g||!1;var h=c[0];a=iee(a,b,c,e);if(a===null)return!1;if(g&&c[0]-h<d.count){if(c[0]<b.length)return!1;a*=Math.pow(10,
d.count-(c[0]-h))}f(a);return!0},cee=function(a,b,c,d,e){e=e||!1;for(var f,g=0;g<c.length;g++){f=b;for(var h=c[g],l=e,m=0,q=null,r=a.substring(f[0]).toLowerCase(),w=0;w<h.length;w++){var x=h[w].toLowerCase();if(l&&x.indexOf(r)==0){m=r.length;q=w;break}h[w].length>m&&r.indexOf(x)==0&&(m=h[w].length,q=w)}q!==null&&(f[0]+=m);f=q;if(f!==null)return d(f),!0}return!1},aee=function(a,b){(a=a.substring(b[0]).match(Xde))&&(b[0]+=a[0].length)},iee=function(a,b,c,d,e){b=d>0?b.substring(0,c[0]+d):b;e=e||!1;if(a.oa.gHa){d=
[];for(var f=c[0];f<b.length;f++){var g=b.charCodeAt(f)-a.oa.gHa;d.push(0<=g&&g<=9?String.fromCharCode(g+48):b.charAt(f))}b=d.join("")}else b=b.substring(c[0]);a=b.match(new RegExp("^"+(e?"[+-]?":"")+"d+"));if(!a)return null;c[0]+=a[0].length;return parseInt(a[0],10)},$de=function(){};$de.prototype.Ba=!1;
}catch(e){_._DumpException(e)}
var Wde,Xde,Yde;Wde=/^[]/;Xde=/^[]+/;_.Zde=function(a){this.ka=[];this.oa=_.RE;if(typeof a=="number"){a>11&&(a=10);if(a<4)var b=this.oa.Ci[a];else a<8?b=this.oa.Ji[a-4]:(b=this.oa.jj[a-8],b=b.replace("{1}",this.oa.Ci[a-8]),b=b.replace("{0}",this.oa.Ji[a-8]));Yde(this,b)}else Yde(this,a)};
Yde=function(a,b){for(var c=!1,d="",e=0;e<b.length;e++){var f=b.charAt(e);if(Wde.test(f))for(d.length>0&&(a.ka.push({text:d,count:0,d1a:!1,numeric:!1}),d=""),a.ka.push({text:" ",count:0,d1a:!1,numeric:!1});e<b.length-1&&b.charAt(e+1)==" ";)e++;else if(c)f=="'"?e+1<b.length&&b.charAt(e+1)=="'"?(d+="'",e++):c=!1:d+=f;else if("GyMdkHmsSEDabBhKzZvQL".indexOf(f)>=0){d.length>0&&(a.ka.push({text:d,count:0,d1a:!1,numeric:!1}),d="");for(var g=b.charAt(e),h=e+1;h<b.length&&b.charAt(h)==g;)h++;g=h-e;g<=0?h=
!1:(h="MydhHmsSDkK".indexOf(f),h=h>0||h==0&&g<3);a.ka.push({text:f,count:g,d1a:!1,numeric:h});e+=g-1}else f=="'"?e+1<b.length&&b.charAt(e+1)=="'"?(d+="'",e++):c=!0:d+=f}d.length>0&&a.ka.push({text:d,count:0,d1a:!1,numeric:!1});b=!1;for(c=0;c<a.ka.length;c++)a.ka[c].numeric?!b&&c+1<a.ka.length&&a.ka[c+1].numeric&&(b=!0,a.ka[c].d1a=!0):b=!1};
_.Zde.prototype.parse=function(a,b,c){var d=!1,e=!1;c&&(d=c.kBh||!1,e=c.validate||!1);if(d)for(c=0;c<this.ka.length;c++){var f=this.ka[c];if(f.count>0&&("abBhHkKm".indexOf(f.text.charAt(0))<0||f.count>2||f.d1a))throw Error("mi"+f.text.charAt(0));}f=new $de;c=[0];f.Ka=-1;for(var g=0;g<this.ka.length&&!(d&&c[0]>=a.length);g++){if(this.ka[g].count==0){a:{var h=a;var l=c,m=this.ka[g],q=d;if(m.text.match(Wde)!=null){if(m=l[0],aee(h,l),l[0]>m){h=!0;break a}}else{if(h.indexOf(m.text,l[0])==l[0]){l[0]+=
m.text.length;h=!0;break a}if(q&&m.text.indexOf(h.substring(l[0]))==0){l[0]+=h.length-l[0];h=!0;break a}}h=!1}if(h)continue;return 0}if(this.ka[g].d1a){a:{l=a;m=c;q=g;var r=m[0],w=0;for(h=q;h<this.ka.length;h++){var x=this.ka[h],B=x.count;if(B===0)break;if(h==q&&(B-=w,w++,B==0)){h=0;break a}var C=h>q&&x.numeric,N=m[0];if(!bee(this,l,m,x,B,f,!1)||C&&m[0]-N<B)h=q-1,m[0]=r}h-=q}if(h<=0)return 0;g+=h-1}else if(!bee(this,a,c,this.ka[g],0,f,d))return 0}a:{a=e;if(b==null)throw Error("ni");f.era!=void 0&&
f.year!=void 0&&f.era==0&&f.year>0&&(f.year=-(f.year-1));f.year!=void 0&&b.setFullYear(f.year);d=b.getDate();b.setDate(1);f.month!=void 0&&b.setMonth(f.month);f.day!=void 0?b.setDate(f.day):(e=_.o6d(b.getFullYear(),b.getMonth()),b.setDate(d>e?e:d));typeof b.setHours==="function"&&(f.hours==void 0&&(f.hours=b.getHours()),f.hours<12&&(f.Ga!=void 0&&f.Ga>0?f.hours+=12:f.wa!==void 0&&("isPm noon afternoon1 afternoon2 evening1 evening2".split(" ").includes(f.wa)||["night1","night2"].includes(f.wa)&&f.hours>=
6)&&(f.hours+=12)),b.setHours(f.hours));typeof b.setMinutes==="function"&&f.minutes!=void 0&&b.setMinutes(f.minutes);typeof b.setSeconds==="function"&&f.VO!=void 0&&b.setSeconds(f.VO);typeof b.setMilliseconds==="function"&&f.ka!=void 0&&b.setMilliseconds(f.ka);if(a&&(f.year&&f.year!=b.getFullYear()||f.month&&f.month!=b.getMonth()||f.day&&f.day!=b.getDate()||f.hours&&f.hours>=24||f.minutes&&f.minutes>=60||f.VO&&f.VO>=60||f.ka&&f.ka>=1E3))b=!1;else{f.Aa!=void 0&&(a=b.getTimezoneOffset(),b.setTime(b.getTime()+
(f.Aa-a)*6E4));f.Ba&&(a=new Date,a.setFullYear(a.getFullYear()-80),b.getTime()<a.getTime()&&b.setFullYear(a.getFullYear()+100));if(f.oa!=void 0)if(f.day==void 0)f=(7+f.oa-b.getDay())%7,f>3&&(f-=7),a=b.getMonth(),b.setDate(b.getDate()+f),b.getMonth()!=a&&b.setDate(b.getDate()+(f>0?-7:7));else if(f.oa!=b.getDay()){b=!1;break a}b=!0}}return b?c[0]:0};
var bee=function(a,b,c,d,e,f,g){aee(b,c);if(d.numeric&&e>0&&c[0]+e>b.length)return!1;switch(d.text.charAt(0)){case "G":return cee(b,c,[a.oa.kj],function(h){return f.era=h}),!0;case "M":case "L":return dee(a,b,c,e,d,f);case "E":return cee(b,c,[a.oa.aj,a.oa.Yi],function(h){return f.oa=h});case "B":case "b":return e=[],a=[[].concat(a.oa.hj)],e.push("isAm"),e.push("isPm"),b=cee(b,c,a,function(h){return f.Ka=h},g),f.wa=e[f.Ka],g?b:!0;case "a":return b=cee(b,c,[a.oa.hj],function(h){return f.Ga=h},g),g?
b:!0;case "y":return eee(a,b,c,d,e,f);case "Q":return cee(b,c,[a.oa.lj,a.oa.mj],function(h){f.month=h*3;f.day=1});case "d":return fee(a,b,c,d,e,function(h){f.day=h}),!0;case "S":return gee(a,b,c,e,f);case "h":case "K":case "H":case "k":return b=fee(a,b,c,d,e,function(h){f.hours=d.text.charAt(0)==="h"&&h===12?0:h},g),g?b:!0;case "m":return b=fee(a,b,c,d,e,function(h){f.minutes=h},g),g?b:!0;case "s":return fee(a,b,c,d,e,function(h){f.VO=h}),!0;case "z":case "Z":case "v":return hee(a,b,c,f);default:return!1}},
eee=function(a,b,c,d,e,f){var g=c[0];e=iee(a,b,c,e);e===null&&(e=iee(a,b,c,0,!0));if(e===null)return!1;e>=0&&c[0]-g==2&&d.count==2?(a=e,b=(new Date).getFullYear()-80,c=b%100,f.Ba=a==c,a+=Math.floor(b/100)*100+(a<c?100:0),f.year=a):f.year=e;return!0},dee=function(a,b,c,d,e,f){return e.numeric&&fee(a,b,c,e,d,function(g){f.month=g-1})?!0:cee(b,c,[a.oa.Wi,a.oa.Mi,a.oa.Xi,a.oa.nj],function(g){f.month=g})},gee=function(a,b,c,d,e){var f=c[0];a=iee(a,b,c,d);if(a===null)return!1;c=c[0]-f;e.ka=c<3?a*Math.pow(10,
3-c):Math.round(a/Math.pow(10,c-3));return!0},hee=function(a,b,c,d){b.indexOf("GMT",c[0])==c[0]&&(c[0]+=3);if(c[0]>=b.length)return d.Aa=0,!0;var e=c[0],f=iee(a,b,c,0,!0);if(f===null)return!1;if(c[0]<b.length&&b.charAt(c[0])==":"){var g=f*60;c[0]++;f=iee(a,b,c,0);if(f===null)return!1;g+=f}else g=f,g=g<24&&c[0]-e<=3?g*60:g%100+g/100*60;d.Aa=-g;return!0},fee=function(a,b,c,d,e,f,g){g=g||!1;var h=c[0];a=iee(a,b,c,e);if(a===null)return!1;if(g&&c[0]-h<d.count){if(c[0]<b.length)return!1;a*=Math.pow(10,
d.count-(c[0]-h))}f(a);return!0},cee=function(a,b,c,d,e){e=e||!1;for(var f,g=0;g<c.length;g++){f=b;for(var h=c[g],l=e,m=0,q=null,r=a.substring(f[0]).toLowerCase(),w=0;w<h.length;w++){var x=h[w].toLowerCase();if(l&&x.indexOf(r)==0){m=r.length;q=w;break}h[w].length>m&&r.indexOf(x)==0&&(m=h[w].length,q=w)}q!==null&&(f[0]+=m);f=q;if(f!==null)return d(f),!0}return!1},aee=function(a,b){(a=a.substring(b[0]).match(Xde))&&(b[0]+=a[0].length)},iee=function(a,b,c,d,e){b=d>0?b.substring(0,c[0]+d):b;e=e||!1;if(a.oa.gHa){d=
[];for(var f=c[0];f<b.length;f++){var g=b.charCodeAt(f)-a.oa.gHa;d.push(0<=g&&g<=9?String.fromCharCode(g+48):b.charAt(f))}b=d.join("")}else b=b.substring(c[0]);a=b.match(new RegExp("^"+(e?"[+-]?":"")+"d+"));if(!a)return null;c[0]+=a[0].length;return parseInt(a[0],10)},$de=function(){};$de.prototype.Ba=!1;
}catch(e){_._DumpException(e)
var Wde,Xde,Yde;Wde=/^[]/;Xde=/^[]+/;_.Zde=function(a){this.ka=[];this.oa=_.RE;if(typeof a=="number"){a>11&&(a=10);if(a<4)var b=this.oa.Ci[a];else a<8?b=this.oa.Ji[a-4]:(b=this.oa.jj[a-8],b=b.replace("{1}",this.oa.Ci[a-8]),b=b.replace("{0}",this.oa.Ji[a-8]));Yde(this,b)}else Yde(this,a)};
Yde=function(a,b){for(var c=!1,d="",e=0;e<b.length;e++){var f=b.charAt(e);if(Wde.test(f))for(d.length>0&&(a.ka.push({text:d,count:0,d1a:!1,numeric:!1}),d=""),a.ka.push({text:" ",count:0,d1a:!1,numeric:!1});e<b.length-1&&b.charAt(e+1)==" ";)e++;else if(c)f=="'"?e+1<b.length&&b.charAt(e+1)=="'"?(d+="'",e++):c=!1:d+=f;else if("GyMdkHmsSEDabBhKzZvQL".indexOf(f)>=0){d.length>0&&(a.ka.push({text:d,count:0,d1a:!1,numeric:!1}),d="");for(var g=b.charAt(e),h=e+1;h<b.length&&b.charAt(h)==g;)h++;g=h-e;g<=0?h=
!1:(h="MydhHmsSDkK".indexOf(f),h=h>0||h==0&&g<3);a.ka.push({text:f,count:g,d1a:!1,numeric:h});e+=g-1}else f=="'"?e+1<b.length&&b.charAt(e+1)=="'"?(d+="'",e++):c=!0:d+=f}d.length>0&&a.ka.push({text:d,count:0,d1a:!1,numeric:!1});b=!1;for(c=0;c<a.ka.length;c++)a.ka[c].numeric?!b&&c+1<a.ka.length&&a.ka[c+1].numeric&&(b=!0,a.ka[c].d1a=!0):b=!1};
_.Zde.prototype.parse=function(a,b,c){var d=!1,e=!1;c&&(d=c.kBh||!1,e=c.validate||!1);if(d)for(c=0;c<this.ka.length;c++){var f=this.ka[c];if(f.count>0&&("abBhHkKm".indexOf(f.text.charAt(0))<0||f.count>2||f.d1a))throw Error("mi"+f.text.charAt(0));}f=new $de;c=[0];f.Ka=-1;for(var g=0;g<this.ka.length&&!(d&&c[0]>=a.length);g++){if(this.ka[g].count==0){a:{var h=a;var l=c,m=this.ka[g],q=d;if(m.text.match(Wde)!=null){if(m=l[0],aee(h,l),l[0]>m){h=!0;break a}}else{if(h.indexOf(m.text,l[0])==l[0]){l[0]+=
m.text.length;h=!0;break a}if(q&&m.text.indexOf(h.substring(l[0]))==0){l[0]+=h.length-l[0];h=!0;break a}}h=!1}if(h)continue;return 0}if(this.ka[g].d1a){a:{l=a;m=c;q=g;var r=m[0],w=0;for(h=q;h<this.ka.length;h++){var x=this.ka[h],B=x.count;if(B===0)break;if(h==q&&(B-=w,w++,B==0)){h=0;break a}var C=h>q&&x.numeric,N=m[0];if(!bee(this,l,m,x,B,f,!1)||C&&m[0]-N<B)h=q-1,m[0]=r}h-=q}if(h<=0)return 0;g+=h-1}else if(!bee(this,a,c,this.ka[g],0,f,d))return 0}a:{a=e;if(b==null)throw Error("ni");f.era!=void 0&&
f.year!=void 0&&f.era==0&&f.year>0&&(f.year=-(f.year-1));f.year!=void 0&&b.setFullYear(f.year);d=b.getDate();b.setDate(1);f.month!=void 0&&b.setMonth(f.month);f.day!=void 0?b.setDate(f.day):(e=_.o6d(b.getFullYear(),b.getMonth()),b.setDate(d>e?e:d));typeof b.setHours==="function"&&(f.hours==void 0&&(f.hours=b.getHours()),f.hours<12&&(f.Ga!=void 0&&f.Ga>0?f.hours+=12:f.wa!==void 0&&("isPm noon afternoon1 afternoon2 evening1 evening2".split(" ").includes(f.wa)||["night1","night2"].includes(f.wa)&&f.hours>=
6)&&(f.hours+=12)),b.setHours(f.hours));typeof b.setMinutes==="function"&&f.minutes!=void 0&&b.setMinutes(f.minutes);typeof b.setSeconds==="function"&&f.VO!=void 0&&b.setSeconds(f.VO);typeof b.setMilliseconds==="function"&&f.ka!=void 0&&b.setMilliseconds(f.ka);if(a&&(f.year&&f.year!=b.getFullYear()||f.month&&f.month!=b.getMonth()||f.day&&f.day!=b.getDate()||f.hours&&f.hours>=24||f.minutes&&f.minutes>=60||f.VO&&f.VO>=60||f.ka&&f.ka>=1E3))b=!1;else{f.Aa!=void 0&&(a=b.getTimezoneOffset(),b.setTime(b.getTime()+
(f.Aa-a)*6E4));f.Ba&&(a=new Date,a.setFullYear(a.getFullYear()-80),b.getTime()<a.getTime()&&b.setFullYear(a.getFullYear()+100));if(f.oa!=void 0)if(f.day==void 0)f=(7+f.oa-b.getDay())%7,f>3&&(f-=7),a=b.getMonth(),b.setDate(b.getDate()+f),b.getMonth()!=a&&b.setDate(b.getDate()+(f>0?-7:7));else if(f.oa!=b.getDay()){b=!1;break a}b=!0}}return b?c[0]:0};
var bee=function(a,b,c,d,e,f,g){aee(b,c);if(d.numeric&&e>0&&c[0]+e>b.length)return!1;switch(d.text.charAt(0)){case "G":return cee(b,c,[a.oa.kj],function(h){return f.era=h}),!0;case "M":case "L":return dee(a,b,c,e,d,f);case "E":return cee(b,c,[a.oa.aj,a.oa.Yi],function(h){return f.oa=h});case "B":case "b":return e=[],a=[[].concat(a.oa.hj)],e.push("isAm"),e.push("isPm"),b=cee(b,c,a,function(h){return f.Ka=h},g),f.wa=e[f.Ka],g?b:!0;case "a":return b=cee(b,c,[a.oa.hj],function(h){return f.Ga=h},g),g?
b:!0;case "y":return eee(a,b,c,d,e,f);case "Q":return cee(b,c,[a.oa.lj,a.oa.mj],function(h){f.month=h*3;f.day=1});case "d":return fee(a,b,c,d,e,function(h){f.day=h}),!0;case "S":return gee(a,b,c,e,f);case "h":case "K":case "H":case "k":return b=fee(a,b,c,d,e,function(h){f.hours=d.text.charAt(0)==="h"&&h===12?0:h},g),g?b:!0;case "m":return b=fee(a,b,c,d,e,function(h){f.minutes=h},g),g?b:!0;case "s":return fee(a,b,c,d,e,function(h){f.VO=h}),!0;case "z":case "Z":case "v":return hee(a,b,c,f);default:return!1}},
eee=function(a,b,c,d,e,f){var g=c[0];e=iee(a,b,c,e);e===null&&(e=iee(a,b,c,0,!0));if(e===null)return!1;e>=0&&c[0]-g==2&&d.count==2?(a=e,b=(new Date).getFullYear()-80,c=b%100,f.Ba=a==c,a+=Math.floor(b/100)*100+(a<c?100:0),f.year=a):f.year=e;return!0},dee=function(a,b,c,d,e,f){return e.numeric&&fee(a,b,c,e,d,function(g){f.month=g-1})?!0:cee(b,c,[a.oa.Wi,a.oa.Mi,a.oa.Xi,a.oa.nj],function(g){f.month=g})},gee=function(a,b,c,d,e){var f=c[0];a=iee(a,b,c,d);if(a===null)return!1;c=c[0]-f;e.ka=c<3?a*Math.pow(10,
3-c):Math.round(a/Math.pow(10,c-3));return!0},hee=function(a,b,c,d){b.indexOf("GMT",c[0])==c[0]&&(c[0]+=3);if(c[0]>=b.length)return d.Aa=0,!0;var e=c[0],f=iee(a,b,c,0,!0);if(f===null)return!1;if(c[0]<b.length&&b.charAt(c[0])==":"){var g=f*60;c[0]++;f=iee(a,b,c,0);if(f===null)return!1;g+=f}else g=f,g=g<24&&c[0]-e<=3?g*60:g%100+g/100*60;d.Aa=-g;return!0},fee=function(a,b,c,d,e,f,g){g=g||!1;var h=c[0];a=iee(a,b,c,e);if(a===null)return!1;if(g&&c[0]-h<d.count){if(c[0]<b.length)return!1;a*=Math.pow(10,
d.count-(c[0]-h))}f(a);return!0},cee=function(a,b,c,d,e){e=e||!1;for(var f,g=0;g<c.length;g++){f=b;for(var h=c[g],l=e,m=0,q=null,r=a.substring(f[0]).toLowerCase(),w=0;w<h.length;w++){var x=h[w].toLowerCase();if(l&&x.indexOf(r)==0){m=r.length;q=w;break}h[w].length>m&&r.indexOf(x)==0&&(m=h[w].length,q=w)}q!==null&&(f[0]+=m);f=q;if(f!==null)return d(f),!0}return!1},aee=function(a,b){(a=a.substring(b[0]).match(Xde))&&(b[0]+=a[0].length)},iee=function(a,b,c,d,e){b=d>0?b.substring(0,c[0]+d):b;e=e||!1;if(a.oa.gHa){d=
[];for(var f=c[0];f<b.length;f++){var g=b.charCodeAt(f)-a.oa.gHa;d.push(0<=g&&g<=9?String.fromCharCode(g+48):b.charAt(f))}b=d.join("")}else b=b.substring(c[0]);a=b.match(new RegExp("^"+(e?"[+-]?":"")+"\\d+"));if(!a)return null;c[0]+=a[0].length;return parseInt(a[0],10)},$de=function(){};$de.prototype.Ba=!1;
}catch(e){_._DumpException(e)
var Wde,Xde,Yde;Wde=/^[]/;Xde=/^[]+/;_.Zde=function(a){this.ka=[];this.oa=_.RE;if(typeof a=="number"){a>11&&(a=10);if(a<4)var b=this.oa.Ci[a];else a<8?b=this.oa.Ji[a-4]:(b=this.oa.jj[a-8],b=b.replace("{1}",this.oa.Ci[a-8]),b=b.replace("{0}",this.oa.Ji[a-8]));Yde(this,b)}else Yde(this,a)};
Yde=function(a,b){for(var c=!1,d="",e=0;e<b.length;e++){var f=b.charAt(e);if(Wde.test(f))for(d.length>0&&(a.ka.push({text:d,count:0,d1a:!1,numeric:!1}),d=""),a.ka.push({text:" ",count:0,d1a:!1,numeric:!1});e<b.length-1&&b.charAt(e+1)==" ";)e++;else if(c)f=="'"?e+1<b.length&&b.charAt(e+1)=="'"?(d+="'",e++):c=!1:d+=f;else if("GyMdkHmsSEDabBhKzZvQL".indexOf(f)>=0){d.length>0&&(a.ka.push({text:d,count:0,d1a:!1,numeric:!1}),d="");for(var g=b.charAt(e),h=e+1;h<b.length&&b.charAt(h)==g;)h++;g=h-e;g<=0?h=
!1:(h="MydhHmsSDkK".indexOf(f),h=h>0||h==0&&g<3);a.ka.push({text:f,count:g,d1a:!1,numeric:h});e+=g-1}else f=="'"?e+1<b.length&&b.charAt(e+1)=="'"?(d+="'",e++):c=!0:d+=f}d.length>0&&a.ka.push({text:d,count:0,d1a:!1,numeric:!1});b=!1;for(c=0;c<a.ka.length;c++)a.ka[c].numeric?!b&&c+1<a.ka.length&&a.ka[c+1].numeric&&(b=!0,a.ka[c].d1a=!0):b=!1};
_.Zde.prototype.parse=function(a,b,c){var d=!1,e=!1;c&&(d=c.kBh||!1,e=c.validate||!1);if(d)for(c=0;c<this.ka.length;c++){var f=this.ka[c];if(f.count>0&&("abBhHkKm".indexOf(f.text.charAt(0))<0||f.count>2||f.d1a))throw Error("mi"+f.text.charAt(0));}f=new $de;c=[0];f.Ka=-1;for(var g=0;g<this.ka.length&&!(d&&c[0]>=a.length);g++){if(this.ka[g].count==0){a:{var h=a;var l=c,m=this.ka[g],q=d;if(m.text.match(Wde)!=null){if(m=l[0],aee(h,l),l[0]>m){h=!0;break a}}else{if(h.indexOf(m.text,l[0])==l[0]){l[0]+=
m.text.length;h=!0;break a}if(q&&m.text.indexOf(h.substring(l[0]))==0){l[0]+=h.length-l[0];h=!0;break a}}h=!1}if(h)continue;return 0}if(this.ka[g].d1a){a:{l=a;m=c;q=g;var r=m[0],w=0;for(h=q;h<this.ka.length;h++){var x=this.ka[h],B=x.count;if(B===0)break;if(h==q&&(B-=w,w++,B==0)){h=0;break a}var C=h>q&&x.numeric,N=m[0];if(!bee(this,l,m,x,B,f,!1)||C&&m[0]-N<B)h=q-1,m[0]=r}h-=q}if(h<=0)return 0;g+=h-1}else if(!bee(this,a,c,this.ka[g],0,f,d))return 0}a:{a=e;if(b==null)throw Error("ni");f.era!=void 0&&
f.year!=void 0&&f.era==0&&f.year>0&&(f.year=-(f.year-1));f.year!=void 0&&b.setFullYear(f.year);d=b.getDate();b.setDate(1);f.month!=void 0&&b.setMonth(f.month);f.day!=void 0?b.setDate(f.day):(e=_.o6d(b.getFullYear(),b.getMonth()),b.setDate(d>e?e:d));typeof b.setHours==="function"&&(f.hours==void 0&&(f.hours=b.getHours()),f.hours<12&&(f.Ga!=void 0&&f.Ga>0?f.hours+=12:f.wa!==void 0&&("isPm noon afternoon1 afternoon2 evening1 evening2".split(" ").includes(f.wa)||["night1","night2"].includes(f.wa)&&f.hours>=
6)&&(f.hours+=12)),b.setHours(f.hours));typeof b.setMinutes==="function"&&f.minutes!=void 0&&b.setMinutes(f.minutes);typeof b.setSeconds==="function"&&f.VO!=void 0&&b.setSeconds(f.VO);typeof b.setMilliseconds==="function"&&f.ka!=void 0&&b.setMilliseconds(f.ka);if(a&&(f.year&&f.year!=b.getFullYear()||f.month&&f.month!=b.getMonth()||f.day&&f.day!=b.getDate()||f.hours&&f.hours>=24||f.minutes&&f.minutes>=60||f.VO&&f.VO>=60||f.ka&&f.ka>=1E3))b=!1;else{f.Aa!=void 0&&(a=b.getTimezoneOffset(),b.setTime(b.getTime()+
(f.Aa-a)*6E4));f.Ba&&(a=new Date,a.setFullYear(a.getFullYear()-80),b.getTime()<a.getTime()&&b.setFullYear(a.getFullYear()+100));if(f.oa!=void 0)if(f.day==void 0)f=(7+f.oa-b.getDay())%7,f>3&&(f-=7),a=b.getMonth(),b.setDate(b.getDate()+f),b.getMonth()!=a&&b.setDate(b.getDate()+(f>0?-7:7));else if(f.oa!=b.getDay()){b=!1;break a}b=!0}}return b?c[0]:0};
var bee=function(a,b,c,d,e,f,g){aee(b,c);if(d.numeric&&e>0&&c[0]+e>b.length)return!1;switch(d.text.charAt(0)){case "G":return cee(b,c,[a.oa.kj],function(h){return f.era=h}),!0;case "M":case "L":return dee(a,b,c,e,d,f);case "E":return cee(b,c,[a.oa.aj,a.oa.Yi],function(h){return f.oa=h});case "B":case "b":return e=[],a=[[].concat(a.oa.hj)],e.push("isAm"),e.push("isPm"),b=cee(b,c,a,function(h){return f.Ka=h},g),f.wa=e[f.Ka],g?b:!0;case "a":return b=cee(b,c,[a.oa.hj],function(h){return f.Ga=h},g),g?
b:!0;case "y":return eee(a,b,c,d,e,f);case "Q":return cee(b,c,[a.oa.lj,a.oa.mj],function(h){f.month=h*3;f.day=1});case "d":return fee(a,b,c,d,e,function(h){f.day=h}),!0;case "S":return gee(a,b,c,e,f);case "h":case "K":case "H":case "k":return b=fee(a,b,c,d,e,function(h){f.hours=d.text.charAt(0)==="h"&&h===12?0:h},g),g?b:!0;case "m":return b=fee(a,b,c,d,e,function(h){f.minutes=h},g),g?b:!0;case "s":return fee(a,b,c,d,e,function(h){f.VO=h}),!0;case "z":case "Z":case "v":return hee(a,b,c,f);default:return!1}},
eee=function(a,b,c,d,e,f){var g=c[0];e=iee(a,b,c,e);e===null&&(e=iee(a,b,c,0,!0));if(e===null)return!1;e>=0&&c[0]-g==2&&d.count==2?(a=e,b=(new Date).getFullYear()-80,c=b%100,f.Ba=a==c,a+=Math.floor(b/100)*100+(a<c?100:0),f.year=a):f.year=e;return!0},dee=function(a,b,c,d,e,f){return e.numeric&&fee(a,b,c,e,d,function(g){f.month=g-1})?!0:cee(b,c,[a.oa.Wi,a.oa.Mi,a.oa.Xi,a.oa.nj],function(g){f.month=g})},gee=function(a,b,c,d,e){var f=c[0];a=iee(a,b,c,d);if(a===null)return!1;c=c[0]-f;e.ka=c<3?a*Math.pow(10,
3-c):Math.round(a/Math.pow(10,c-3));return!0},hee=function(a,b,c,d){b.indexOf("GMT",c[0])==c[0]&&(c[0]+=3);if(c[0]>=b.length)return d.Aa=0,!0;var e=c[0],f=iee(a,b,c,0,!0);if(f===null)return!1;if(c[0]<b.length&&b.charAt(c[0])==":"){var g=f*60;c[0]++;f=iee(a,b,c,0);if(f===null)return!1;g+=f}else g=f,g=g<24&&c[0]-e<=3?g*60:g%100+g/100*60;d.Aa=-g;return!0},fee=function(a,b,c,d,e,f,g){g=g||!1;var h=c[0];a=iee(a,b,c,e);if(a===null)return!1;if(g&&c[0]-h<d.count){if(c[0]<b.length)return!1;a*=Math.pow(10,
d.count-(c[0]-h))}f(a);return!0},cee=function(a,b,c,d,e){e=e||!1;for(var f,g=0;g<c.length;g++){f=b;for(var h=c[g],l=e,m=0,q=null,r=a.substring(f[0]).toLowerCase(),w=0;w<h.length;w++){var x=h[w].toLowerCase();if(l&&x.indexOf(r)==0){m=r.length;q=w;break}h[w].length>m&&r.indexOf(x)==0&&(m=h[w].length,q=w)}q!==null&&(f[0]+=m);f=q;if(f!==null)return d(f),!0}return!1},aee=function(a,b){(a=a.substring(b[0]).match(Xde))&&(b[0]+=a[0].length)},iee=function(a,b,c,d,e){b=d>0?b.substring(0,c[0]+d):b;e=e||!1;if(a.oa.gHa){d=
[];for(var f=c[0];f<b.length;f++){var g=b.charCodeAt(f)-a.oa.gHa;d.push(0<=g&&g<=9?String.fromCharCode(g+48):b.charAt(f))}b=d.join("")}else b=b.substring(c[0]);a=b.match(new RegExp("^"+(e?"[+-]?":"")+"\\d+"));if(!a)return null;c[0]+=a[0].length;return parseInt(a[0],10)},$de=function(){};$de.prototype.Ba=!1;
}catch(e){_._DumpException(e)
`;

export const tokenizedSampleCode = esprima.tokenize(sampleCode);

export const skippedTokenChars = ["\n", " ", "\t", "\r", ""]
